# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.config/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=( 
    git
    archlinux
    zsh-autosuggestions
    zsh-syntax-highlighting
)



source $ZSH/oh-my-zsh.sh


# Check archlinux plugin commands here
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/archlinux


# Display Pokemon-colorscripts
# Project page: https://gitlab.com/phoneybadger/pokemon-colorscripts#on-other-distros-and-macos



### From this line is for pywal-colors
# Import colorscheme from 'wal' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
# Not supported in the "fish" shell.
#(cat ~/.cache/wal/sequences &)

# Alternative (blocks terminal for 0-3ms)
#cat ~/.cache/wal/sequences

# To add support for TTYs this line can be optionally added.
#source ~/.cache/wal/colors-tty.sh

# My alias 

# alias cty='tty-clock -S -c -C 6 -t -n -D'
alias n='nvim'
alias t='tmux'
alias ta='tmux attach'
alias tl='tmux ls'

# return aliases
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# git aliases
alias gc='git clone '
alias ga='git add . '
alias gcm='git commit -m '
alias gp='git push -u origin '
alias gs='git status '
alias gl='git log --oneline --graph --decorate --all '
alias gd='git diff'
alias gco='git checkout '
alias gb='git branch '
alias gpl='git pull '

# pacman aliases
alias p='sudo pacman -S '
alias pu='sudo pacman -Syu '
alias ps='sudo pacman -Ss '
alias pr='sudo pacman -Rns '
alias pi='p --noconfirm '
alias pl='sudo pacman -Q '
alias pcc='sudo pacman -Scc'

# yay aliases
alias y='yay -S '
alias yu='yay -Syu '
alias ys='yay -Ss '
alias yc='yay -Rns '
alias yi='yay -S --noconfirm '
alias ycc='yay -Scc'
alias yua='yay -Sua '
alias yq='yay -Qu '


# other aliases
alias ll='ls -Alh'
alias ls='lsd --group-dirs first'
alias cat='bat'

alias py='python3'

alias c='sudo rsync -avhW --no-compress --progress '

alias md1='sudo mount /dev/sda5 /mnt/vmachines'
alias md2='sudo mount /dev/sda4 /mnt/windows-drive'
alias web='tmuxifier load-session web-dev'

alias nivm='nvim'
alias cd='z'

alias tk='tmux kill-server'


# Set-up FZF key bindings (CTRL R for fuzzy history finder)
source <(fzf --zsh)

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory


# exports
# export LC_TIME=ur_PK.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH="$HOME/.tmuxifier/bin:$PATH"
export LIBVIRT_DEFAULT_URI='qemu:///system'
eval "$(zoxide init zsh)"
eval "$(tmuxifier init -)"
export PATH=$PATH:/home/ahmad/.spicetify
[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

 . "$HOME/.local/bin/env"

# pnpm
#export PNPM_HOME="/home/medwf/.local/share/pnpm"
#case ":$PATH:" in
#  *":$PNPM_HOME:"*) ;;
#  *) export PATH="$PNPM_HOME:$PATH" ;;
#esac
# pnpm end
