#: black
color0 #2e2e2e
color8 #2e2e2e

#: red
color1  #eb4129
color9 #eb4129

#: green
color2  #abe047
color10 #abe047

#: yellow
color3  #f6c744
color11 #f6c744

#: blue
color4  #47a0f3
color12 #47a0f3

#: magenta
color5  #7b5cb0
color13 #7b5cb0

#: cyan
color6  #64dbed
color14 #64dbed

#: white
color7  #e5e9f0
color15 #e5e9f0
